### ISSUE TITLE
In Jank Stat Aggregator report function frame data is changing.

### ISSUE THREAD

**Issue by mayureshcostco** [android/performance-samples#205]
I have put logs on the jank stat listener its shows a janky frame is found and when I see the results in the report listener it shows the frame is not Janky. Some weird observations I have found with this library.

**Comment by keyboardsurfer** [comment]
Please provide more detail so we can investigate this in detail.

**Comment by LordRaydenMK** [comment]
Since I ran into the same issue, maybe I can provide more details. From `JankStatsAggregator`:

```
  private val listener = JankStats.OnFrameListener { frameData ->
      ++numFrames
      if (frameData.isJank) {
          jankReport.add(frameData)
          if (jankReport.size >= REPORT_BUFFER_LIMIT) {
              issueJankReport("Max buffer size reached")
          }
      }
  }
```

it collects the frames that have `isJank=true` into a list. Later, when `issueJankReport` is called (or buffer capacity is reached) it will use that list for the `OnJankReportListener.onJankReport` callback.

Since only frames that have `isJanke=true` are added to the list, we expect that `OnJankReportListener.onJankReport` contains only frames with `isJank=true`. However in practice this DOES NOT happen.

The problem:

From the [documentation](https://developer.android.com/topic/performance/jankstats#reporting) we see:

> Also, note that the FrameData object sent in the callback is reused on every frame to prevent having to allocate new objects for data reporting. This means that you must copy and cache that data elsewhere since that object should be considered statle and obsolete as soon as the callback returns.

the internal `ArrayList` used by `JankStatsAggregator` outlives the `JankStats.OnFrameListener` so `JankStats` mutates the objects inside it causing wrong data to be reported in `OnJankReportListener.onJankReport`.
