### ISSUE TITLE
Why macrobenchmark module's build.gradle has "isDebuggable = true" 

### ISSUE THREAD

**Issue by hellosagar** [android/performance-samples#267]
Why are we using "isDebuggable = true" in the  [build.gradle](https://github.com/android/performance-samples/blob/dd72076deb931e9efbde28fb023a3fcf031e316e/MacrobenchmarkSample/macrobenchmark/build.gradle.kts#L67) of `macrobenchmark` module.

I was reading the documentation and found that isDebuggable set to `false

Doc [LINK](https://developer.android.com/topic/performance/benchmarking/macrobenchmark-overview#configuration-errors) and codelab [LINK](https://developer.android.com/codelabs/android-macrobenchmark-inspect#3) for  macrobenchmarking and generating the baseline profile.

<img width="931" alt="Screenshot 2023-12-27 at 6 13 45 PM" src="https://github.com/android/performance-samples/assets/50016799/b31a7e18-39da-4038-b868-01dcba4a6197">

<img width="911" alt="Screenshot 2023-12-27 at 6 21 59 PM" src="https://github.com/android/performance-samples/assets/50016799/bd1d75d4-34bf-4262-a4a9-9c7e196e0e30">

**Comment by ChrisCraik** [comment]
Macrobenchmarks have two processes - the target app (app module, app being measured), and the test process (corresponding to the macrobenchmark module)

Macrobench will detect and throw if the target app is debuggable, but debuggable doesn't really matter for the macrobench module, since it's not being measured, and is just a test process, and may benefit from connecting a debugger.

Murat, can you add a comment, and consider clarifying the codelab docs about debuggable, so it's clear it's talking about the app module?
