### ISSUE TITLE
ConstraintLayout vs. LinearLayout sample has nothing to do with Jetpack Benchmark

### ISSUE THREAD

**Issue by sigmabeta** [android/performance-samples#40]
As a consumer of the Jetpack Benchmark docs, which led me to this repository, it's a little strange that that sample is included in this project. It does not appear to make use of the Jetpack Benchmark library and it took me a fair amount of fiddling to realize this (as that project does not build without upgrading various build tools.)

Perhaps it could be moved to another repository?

**Comment by ChrisCraik** [comment]
This repository is intended as a general repository for android performance samples, not just benchmarks. It just happens that benchmark samples are the only recent developments here.

That said, I'd ideally like to move that sample to use Benchmark (since it was written before the benchmark library existed), but we haven't gotten around to it.
