### ISSUE TITLE
The benchmark setup with release target is unrealistic

### ISSUE THREAD

**Issue by yschimke** [android/performance-samples#93]
Seems like  useful sample to show both benchmark and release targets.

**Comment by mlykotom** [comment]
Could you provide more info about the problem you have?

**Comment by yschimke** [comment]
No problem, just a suggestion for the sample.

In the benchmark sample, the build setup uses a release target, which as a sample probably isn't something we would advise developers to follow.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/231923/152798388-ef938ec5-f31d-474d-8a58-af9d77f6f62b.png">

https://github.com/android/performance-samples/blob/main/BenchmarkSample/benchmark/build.gradle

**Comment by yschimke** [comment]
@mlykotom apologies for the terrible bug report, I keep forgetting the context I have in my head when I drop a quick bug.

**Comment by ChrisCraik** [comment]
> the build setup uses a release target, which as a sample probably isn't something we would advise developers to follow.

Why do you say this isn't something to advise? Benchmarks are in their own separate module, so it's not necessary to create a new buildType, separate from release. Nothing should ever take a dependency on a release library module that's only used for tests.

For macrobenchmark, what you're saying is true, which is why [we recently changed it](https://github.com/android/performance-samples/commit/a122b2cd5a1518021585b39ba907f61d56fafd8c) to use a separate `benchmark` build type, since it interacts with the app module. Now both match the Studio module template behavior in Bumblebee - `release` for the (micro)benchmark module, `benchmark` for the macrobench module.

**Comment by yschimke** [comment]
Thanks, I'll close then.
